<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Concur\Api\Normalizer;

use Symfony\Component\Serializer\Exception\InvalidArgumentException;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class EntryPutNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $type === 'Concur\\Api\\Model\\EntryPut';
    }

    public function supportsNormalization($data, $format = null)
    {
        return is_object($data) && get_class($data) === 'Concur\\Api\\Model\\EntryPut';
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (!is_object($data)) {
            throw new InvalidArgumentException();
        }
        $object = new \Concur\Api\Model\EntryPut();
        if (property_exists($data, 'Comment')) {
            $object->setComment($data->{'Comment'});
        }
        if (property_exists($data, 'Custom1')) {
            $object->setCustom1($data->{'Custom1'});
        }
        if (property_exists($data, 'Custom10')) {
            $object->setCustom10($data->{'Custom10'});
        }
        if (property_exists($data, 'Custom11')) {
            $object->setCustom11($data->{'Custom11'});
        }
        if (property_exists($data, 'Custom12')) {
            $object->setCustom12($data->{'Custom12'});
        }
        if (property_exists($data, 'Custom13')) {
            $object->setCustom13($data->{'Custom13'});
        }
        if (property_exists($data, 'Custom14')) {
            $object->setCustom14($data->{'Custom14'});
        }
        if (property_exists($data, 'Custom15')) {
            $object->setCustom15($data->{'Custom15'});
        }
        if (property_exists($data, 'Custom16')) {
            $object->setCustom16($data->{'Custom16'});
        }
        if (property_exists($data, 'Custom17')) {
            $object->setCustom17($data->{'Custom17'});
        }
        if (property_exists($data, 'Custom18')) {
            $object->setCustom18($data->{'Custom18'});
        }
        if (property_exists($data, 'Custom19')) {
            $object->setCustom19($data->{'Custom19'});
        }
        if (property_exists($data, 'Custom2')) {
            $object->setCustom2($data->{'Custom2'});
        }
        if (property_exists($data, 'Custom20')) {
            $object->setCustom20($data->{'Custom20'});
        }
        if (property_exists($data, 'Custom21')) {
            $object->setCustom21($data->{'Custom21'});
        }
        if (property_exists($data, 'Custom22')) {
            $object->setCustom22($data->{'Custom22'});
        }
        if (property_exists($data, 'Custom23')) {
            $object->setCustom23($data->{'Custom23'});
        }
        if (property_exists($data, 'Custom24')) {
            $object->setCustom24($data->{'Custom24'});
        }
        if (property_exists($data, 'Custom25')) {
            $object->setCustom25($data->{'Custom25'});
        }
        if (property_exists($data, 'Custom26')) {
            $object->setCustom26($data->{'Custom26'});
        }
        if (property_exists($data, 'Custom27')) {
            $object->setCustom27($data->{'Custom27'});
        }
        if (property_exists($data, 'Custom28')) {
            $object->setCustom28($data->{'Custom28'});
        }
        if (property_exists($data, 'Custom29')) {
            $object->setCustom29($data->{'Custom29'});
        }
        if (property_exists($data, 'Custom3')) {
            $object->setCustom3($data->{'Custom3'});
        }
        if (property_exists($data, 'Custom30')) {
            $object->setCustom30($data->{'Custom30'});
        }
        if (property_exists($data, 'Custom31')) {
            $object->setCustom31($data->{'Custom31'});
        }
        if (property_exists($data, 'Custom32')) {
            $object->setCustom32($data->{'Custom32'});
        }
        if (property_exists($data, 'Custom33')) {
            $object->setCustom33($data->{'Custom33'});
        }
        if (property_exists($data, 'Custom34')) {
            $object->setCustom34($data->{'Custom34'});
        }
        if (property_exists($data, 'Custom35')) {
            $object->setCustom35($data->{'Custom35'});
        }
        if (property_exists($data, 'Custom36')) {
            $object->setCustom36($data->{'Custom36'});
        }
        if (property_exists($data, 'Custom37')) {
            $object->setCustom37($data->{'Custom37'});
        }
        if (property_exists($data, 'Custom38')) {
            $object->setCustom38($data->{'Custom38'});
        }
        if (property_exists($data, 'Custom39')) {
            $object->setCustom39($data->{'Custom39'});
        }
        if (property_exists($data, 'Custom4')) {
            $object->setCustom4($data->{'Custom4'});
        }
        if (property_exists($data, 'Custom40')) {
            $object->setCustom40($data->{'Custom40'});
        }
        if (property_exists($data, 'Custom5')) {
            $object->setCustom5($data->{'Custom5'});
        }
        if (property_exists($data, 'Custom6')) {
            $object->setCustom6($data->{'Custom6'});
        }
        if (property_exists($data, 'Custom7')) {
            $object->setCustom7($data->{'Custom7'});
        }
        if (property_exists($data, 'Custom8')) {
            $object->setCustom8($data->{'Custom8'});
        }
        if (property_exists($data, 'Custom9')) {
            $object->setCustom9($data->{'Custom9'});
        }
        if (property_exists($data, 'Description')) {
            $object->setDescription($data->{'Description'});
        }
        if (property_exists($data, 'ExchangeRate')) {
            $object->setExchangeRate($data->{'ExchangeRate'});
        }
        if (property_exists($data, 'ExpenseTypeCode')) {
            $object->setExpenseTypeCode($data->{'ExpenseTypeCode'});
        }
        if (property_exists($data, 'IsBillable')) {
            $object->setIsBillable($data->{'IsBillable'});
        }
        if (property_exists($data, 'IsPersonal')) {
            $object->setIsPersonal($data->{'IsPersonal'});
        }
        if (property_exists($data, 'Journey')) {
            $object->setJourney($this->denormalizer->denormalize($data->{'Journey'}, 'Concur\\Api\\Model\\Journey', 'json', $context));
        }
        if (property_exists($data, 'LocationID')) {
            $object->setLocationID($data->{'LocationID'});
        }
        if (property_exists($data, 'OrgUnit1')) {
            $object->setOrgUnit1($data->{'OrgUnit1'});
        }
        if (property_exists($data, 'OrgUnit2')) {
            $object->setOrgUnit2($data->{'OrgUnit2'});
        }
        if (property_exists($data, 'OrgUnit3')) {
            $object->setOrgUnit3($data->{'OrgUnit3'});
        }
        if (property_exists($data, 'OrgUnit4')) {
            $object->setOrgUnit4($data->{'OrgUnit4'});
        }
        if (property_exists($data, 'OrgUnit5')) {
            $object->setOrgUnit5($data->{'OrgUnit5'});
        }
        if (property_exists($data, 'OrgUnit6')) {
            $object->setOrgUnit6($data->{'OrgUnit6'});
        }
        if (property_exists($data, 'PaymentTypeID')) {
            $object->setPaymentTypeID($data->{'PaymentTypeID'});
        }
        if (property_exists($data, 'ReportID')) {
            $object->setReportID($data->{'ReportID'});
        }
        if (property_exists($data, 'TaxReceiptType')) {
            $object->setTaxReceiptType($data->{'TaxReceiptType'});
        }
        if (property_exists($data, 'TransactionAmount')) {
            $object->setTransactionAmount($data->{'TransactionAmount'});
        }
        if (property_exists($data, 'TransactionCurrencyCode')) {
            $object->setTransactionCurrencyCode($data->{'TransactionCurrencyCode'});
        }
        if (property_exists($data, 'TransactionDate')) {
            $object->setTransactionDate(\DateTime::createFromFormat("Y-m-d\TH:i:sP", $data->{'TransactionDate'}));
        }
        if (property_exists($data, 'VendorDescription')) {
            $object->setVendorDescription($data->{'VendorDescription'});
        }
        if (property_exists($data, 'VendorListItemID')) {
            $object->setVendorListItemID($data->{'VendorListItemID'});
        }

        return $object;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $data = new \stdClass();
        if (null !== $object->getComment()) {
            $data->{'Comment'} = $object->getComment();
        }
        if (null !== $object->getCustom1()) {
            $data->{'Custom1'} = $object->getCustom1();
        }
        if (null !== $object->getCustom10()) {
            $data->{'Custom10'} = $object->getCustom10();
        }
        if (null !== $object->getCustom11()) {
            $data->{'Custom11'} = $object->getCustom11();
        }
        if (null !== $object->getCustom12()) {
            $data->{'Custom12'} = $object->getCustom12();
        }
        if (null !== $object->getCustom13()) {
            $data->{'Custom13'} = $object->getCustom13();
        }
        if (null !== $object->getCustom14()) {
            $data->{'Custom14'} = $object->getCustom14();
        }
        if (null !== $object->getCustom15()) {
            $data->{'Custom15'} = $object->getCustom15();
        }
        if (null !== $object->getCustom16()) {
            $data->{'Custom16'} = $object->getCustom16();
        }
        if (null !== $object->getCustom17()) {
            $data->{'Custom17'} = $object->getCustom17();
        }
        if (null !== $object->getCustom18()) {
            $data->{'Custom18'} = $object->getCustom18();
        }
        if (null !== $object->getCustom19()) {
            $data->{'Custom19'} = $object->getCustom19();
        }
        if (null !== $object->getCustom2()) {
            $data->{'Custom2'} = $object->getCustom2();
        }
        if (null !== $object->getCustom20()) {
            $data->{'Custom20'} = $object->getCustom20();
        }
        if (null !== $object->getCustom21()) {
            $data->{'Custom21'} = $object->getCustom21();
        }
        if (null !== $object->getCustom22()) {
            $data->{'Custom22'} = $object->getCustom22();
        }
        if (null !== $object->getCustom23()) {
            $data->{'Custom23'} = $object->getCustom23();
        }
        if (null !== $object->getCustom24()) {
            $data->{'Custom24'} = $object->getCustom24();
        }
        if (null !== $object->getCustom25()) {
            $data->{'Custom25'} = $object->getCustom25();
        }
        if (null !== $object->getCustom26()) {
            $data->{'Custom26'} = $object->getCustom26();
        }
        if (null !== $object->getCustom27()) {
            $data->{'Custom27'} = $object->getCustom27();
        }
        if (null !== $object->getCustom28()) {
            $data->{'Custom28'} = $object->getCustom28();
        }
        if (null !== $object->getCustom29()) {
            $data->{'Custom29'} = $object->getCustom29();
        }
        if (null !== $object->getCustom3()) {
            $data->{'Custom3'} = $object->getCustom3();
        }
        if (null !== $object->getCustom30()) {
            $data->{'Custom30'} = $object->getCustom30();
        }
        if (null !== $object->getCustom31()) {
            $data->{'Custom31'} = $object->getCustom31();
        }
        if (null !== $object->getCustom32()) {
            $data->{'Custom32'} = $object->getCustom32();
        }
        if (null !== $object->getCustom33()) {
            $data->{'Custom33'} = $object->getCustom33();
        }
        if (null !== $object->getCustom34()) {
            $data->{'Custom34'} = $object->getCustom34();
        }
        if (null !== $object->getCustom35()) {
            $data->{'Custom35'} = $object->getCustom35();
        }
        if (null !== $object->getCustom36()) {
            $data->{'Custom36'} = $object->getCustom36();
        }
        if (null !== $object->getCustom37()) {
            $data->{'Custom37'} = $object->getCustom37();
        }
        if (null !== $object->getCustom38()) {
            $data->{'Custom38'} = $object->getCustom38();
        }
        if (null !== $object->getCustom39()) {
            $data->{'Custom39'} = $object->getCustom39();
        }
        if (null !== $object->getCustom4()) {
            $data->{'Custom4'} = $object->getCustom4();
        }
        if (null !== $object->getCustom40()) {
            $data->{'Custom40'} = $object->getCustom40();
        }
        if (null !== $object->getCustom5()) {
            $data->{'Custom5'} = $object->getCustom5();
        }
        if (null !== $object->getCustom6()) {
            $data->{'Custom6'} = $object->getCustom6();
        }
        if (null !== $object->getCustom7()) {
            $data->{'Custom7'} = $object->getCustom7();
        }
        if (null !== $object->getCustom8()) {
            $data->{'Custom8'} = $object->getCustom8();
        }
        if (null !== $object->getCustom9()) {
            $data->{'Custom9'} = $object->getCustom9();
        }
        if (null !== $object->getDescription()) {
            $data->{'Description'} = $object->getDescription();
        }
        if (null !== $object->getExchangeRate()) {
            $data->{'ExchangeRate'} = $object->getExchangeRate();
        }
        if (null !== $object->getExpenseTypeCode()) {
            $data->{'ExpenseTypeCode'} = $object->getExpenseTypeCode();
        }
        if (null !== $object->getIsBillable()) {
            $data->{'IsBillable'} = $object->getIsBillable();
        }
        if (null !== $object->getIsPersonal()) {
            $data->{'IsPersonal'} = $object->getIsPersonal();
        }
        if (null !== $object->getJourney()) {
            $data->{'Journey'} = $this->normalizer->normalize($object->getJourney(), 'json', $context);
        }
        if (null !== $object->getLocationID()) {
            $data->{'LocationID'} = $object->getLocationID();
        }
        if (null !== $object->getOrgUnit1()) {
            $data->{'OrgUnit1'} = $object->getOrgUnit1();
        }
        if (null !== $object->getOrgUnit2()) {
            $data->{'OrgUnit2'} = $object->getOrgUnit2();
        }
        if (null !== $object->getOrgUnit3()) {
            $data->{'OrgUnit3'} = $object->getOrgUnit3();
        }
        if (null !== $object->getOrgUnit4()) {
            $data->{'OrgUnit4'} = $object->getOrgUnit4();
        }
        if (null !== $object->getOrgUnit5()) {
            $data->{'OrgUnit5'} = $object->getOrgUnit5();
        }
        if (null !== $object->getOrgUnit6()) {
            $data->{'OrgUnit6'} = $object->getOrgUnit6();
        }
        if (null !== $object->getPaymentTypeID()) {
            $data->{'PaymentTypeID'} = $object->getPaymentTypeID();
        }
        if (null !== $object->getReportID()) {
            $data->{'ReportID'} = $object->getReportID();
        }
        if (null !== $object->getTaxReceiptType()) {
            $data->{'TaxReceiptType'} = $object->getTaxReceiptType();
        }
        if (null !== $object->getTransactionAmount()) {
            $data->{'TransactionAmount'} = $object->getTransactionAmount();
        }
        if (null !== $object->getTransactionCurrencyCode()) {
            $data->{'TransactionCurrencyCode'} = $object->getTransactionCurrencyCode();
        }
        if (null !== $object->getTransactionDate()) {
            $data->{'TransactionDate'} = $object->getTransactionDate()->format("Y-m-d\TH:i:sP");
        }
        if (null !== $object->getVendorDescription()) {
            $data->{'VendorDescription'} = $object->getVendorDescription();
        }
        if (null !== $object->getVendorListItemID()) {
            $data->{'VendorListItemID'} = $object->getVendorListItemID();
        }

        return $data;
    }
}
