<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Concur\Api\Normalizer;

use Symfony\Component\Serializer\Exception\InvalidArgumentException;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class ReportGetNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $type === 'Concur\\Api\\Model\\ReportGet';
    }

    public function supportsNormalization($data, $format = null)
    {
        return is_object($data) && get_class($data) === 'Concur\\Api\\Model\\ReportGet';
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (!is_object($data)) {
            throw new InvalidArgumentException();
        }
        $object = new \Concur\Api\Model\ReportGet();
        if (property_exists($data, 'AmountDueCompanyCard')) {
            $object->setAmountDueCompanyCard($data->{'AmountDueCompanyCard'});
        }
        if (property_exists($data, 'AmountDueEmployee')) {
            $object->setAmountDueEmployee($data->{'AmountDueEmployee'});
        }
        if (property_exists($data, 'ApprovalStatusCode')) {
            $object->setApprovalStatusCode($data->{'ApprovalStatusCode'});
        }
        if (property_exists($data, 'ApprovalStatusName')) {
            $object->setApprovalStatusName($data->{'ApprovalStatusName'});
        }
        if (property_exists($data, 'ApproverLoginID')) {
            $object->setApproverLoginID($data->{'ApproverLoginID'});
        }
        if (property_exists($data, 'ApproverName')) {
            $object->setApproverName($data->{'ApproverName'});
        }
        if (property_exists($data, 'Country')) {
            $object->setCountry($data->{'Country'});
        }
        if (property_exists($data, 'CountrySubdivision')) {
            $object->setCountrySubdivision($data->{'CountrySubdivision'});
        }
        if (property_exists($data, 'CreateDate')) {
            $object->setCreateDate($data->{'CreateDate'});
        }
        if (property_exists($data, 'CurrencyCode')) {
            $object->setCurrencyCode($data->{'CurrencyCode'});
        }
        if (property_exists($data, 'Custom1')) {
            $object->setCustom1($data->{'Custom1'});
        }
        if (property_exists($data, 'Custom10')) {
            $object->setCustom10($data->{'Custom10'});
        }
        if (property_exists($data, 'Custom11')) {
            $object->setCustom11($data->{'Custom11'});
        }
        if (property_exists($data, 'Custom12')) {
            $object->setCustom12($data->{'Custom12'});
        }
        if (property_exists($data, 'Custom13')) {
            $object->setCustom13($data->{'Custom13'});
        }
        if (property_exists($data, 'Custom14')) {
            $object->setCustom14($data->{'Custom14'});
        }
        if (property_exists($data, 'Custom15')) {
            $object->setCustom15($data->{'Custom15'});
        }
        if (property_exists($data, 'Custom16')) {
            $object->setCustom16($data->{'Custom16'});
        }
        if (property_exists($data, 'Custom17')) {
            $object->setCustom17($data->{'Custom17'});
        }
        if (property_exists($data, 'Custom18')) {
            $object->setCustom18($data->{'Custom18'});
        }
        if (property_exists($data, 'Custom19')) {
            $object->setCustom19($data->{'Custom19'});
        }
        if (property_exists($data, 'Custom2')) {
            $object->setCustom2($data->{'Custom2'});
        }
        if (property_exists($data, 'Custom20')) {
            $object->setCustom20($data->{'Custom20'});
        }
        if (property_exists($data, 'Custom3')) {
            $object->setCustom3($data->{'Custom3'});
        }
        if (property_exists($data, 'Custom4')) {
            $object->setCustom4($data->{'Custom4'});
        }
        if (property_exists($data, 'Custom5')) {
            $object->setCustom5($data->{'Custom5'});
        }
        if (property_exists($data, 'Custom6')) {
            $object->setCustom6($data->{'Custom6'});
        }
        if (property_exists($data, 'Custom7')) {
            $object->setCustom7($data->{'Custom7'});
        }
        if (property_exists($data, 'Custom8')) {
            $object->setCustom8($data->{'Custom8'});
        }
        if (property_exists($data, 'Custom9')) {
            $object->setCustom9($data->{'Custom9'});
        }
        if (property_exists($data, 'EverSentBack')) {
            $object->setEverSentBack($data->{'EverSentBack'});
        }
        if (property_exists($data, 'HasException')) {
            $object->setHasException($data->{'HasException'});
        }
        if (property_exists($data, 'ID')) {
            $object->setID($data->{'ID'});
        }
        if (property_exists($data, 'LastComment')) {
            $object->setLastComment($data->{'LastComment'});
        }
        if (property_exists($data, 'LastModifiedDate')) {
            $object->setLastModifiedDate($data->{'LastModifiedDate'});
        }
        if (property_exists($data, 'LedgerName')) {
            $object->setLedgerName($data->{'LedgerName'});
        }
        if (property_exists($data, 'Name')) {
            $object->setName($data->{'Name'});
        }
        if (property_exists($data, 'OrgUnit1')) {
            $object->setOrgUnit1($data->{'OrgUnit1'});
        }
        if (property_exists($data, 'OrgUnit2')) {
            $object->setOrgUnit2($data->{'OrgUnit2'});
        }
        if (property_exists($data, 'OrgUnit3')) {
            $object->setOrgUnit3($data->{'OrgUnit3'});
        }
        if (property_exists($data, 'OrgUnit4')) {
            $object->setOrgUnit4($data->{'OrgUnit4'});
        }
        if (property_exists($data, 'OrgUnit5')) {
            $object->setOrgUnit5($data->{'OrgUnit5'});
        }
        if (property_exists($data, 'OrgUnit6')) {
            $object->setOrgUnit6($data->{'OrgUnit6'});
        }
        if (property_exists($data, 'OwnerLoginID')) {
            $object->setOwnerLoginID($data->{'OwnerLoginID'});
        }
        if (property_exists($data, 'OwnerName')) {
            $object->setOwnerName($data->{'OwnerName'});
        }
        if (property_exists($data, 'PaidDate')) {
            $object->setPaidDate($data->{'PaidDate'});
        }
        if (property_exists($data, 'PaymentStatusCode')) {
            $object->setPaymentStatusCode($data->{'PaymentStatusCode'});
        }
        if (property_exists($data, 'PaymentStatusName')) {
            $object->setPaymentStatusName($data->{'PaymentStatusName'});
        }
        if (property_exists($data, 'PersonalAmount')) {
            $object->setPersonalAmount($data->{'PersonalAmount'});
        }
        if (property_exists($data, 'PolicyID')) {
            $object->setPolicyID($data->{'PolicyID'});
        }
        if (property_exists($data, 'ProcessingPaymentDate')) {
            $object->setProcessingPaymentDate($data->{'ProcessingPaymentDate'});
        }
        if (property_exists($data, 'ReceiptsReceived')) {
            $object->setReceiptsReceived($data->{'ReceiptsReceived'});
        }
        if (property_exists($data, 'SubmitDate')) {
            $object->setSubmitDate($data->{'SubmitDate'});
        }
        if (property_exists($data, 'Total')) {
            $object->setTotal($data->{'Total'});
        }
        if (property_exists($data, 'TotalApprovedAmount')) {
            $object->setTotalApprovedAmount($data->{'TotalApprovedAmount'});
        }
        if (property_exists($data, 'TotalClaimedAmount')) {
            $object->setTotalClaimedAmount($data->{'TotalClaimedAmount'});
        }
        if (property_exists($data, 'URI')) {
            $object->setURI($data->{'URI'});
        }
        if (property_exists($data, 'UserDefinedDate')) {
            $object->setUserDefinedDate($data->{'UserDefinedDate'});
        }
        if (property_exists($data, 'WorkflowActionUrl')) {
            $object->setWorkflowActionUrl($data->{'WorkflowActionUrl'});
        }

        return $object;
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $data = new \stdClass();
        $data->{'AmountDueCompanyCard'} = $object->getAmountDueCompanyCard();
        $data->{'AmountDueEmployee'} = $object->getAmountDueEmployee();
        $data->{'ApprovalStatusCode'} = $object->getApprovalStatusCode();
        $data->{'ApprovalStatusName'} = $object->getApprovalStatusName();
        $data->{'ApproverLoginID'} = $object->getApproverLoginID();
        $data->{'ApproverName'} = $object->getApproverName();
        $data->{'Country'} = $object->getCountry();
        $data->{'CountrySubdivision'} = $object->getCountrySubdivision();
        $data->{'CreateDate'} = $object->getCreateDate();
        $data->{'CurrencyCode'} = $object->getCurrencyCode();
        if (null !== $object->getCustom1()) {
            $data->{'Custom1'} = $object->getCustom1();
        }
        if (null !== $object->getCustom10()) {
            $data->{'Custom10'} = $object->getCustom10();
        }
        if (null !== $object->getCustom11()) {
            $data->{'Custom11'} = $object->getCustom11();
        }
        if (null !== $object->getCustom12()) {
            $data->{'Custom12'} = $object->getCustom12();
        }
        if (null !== $object->getCustom13()) {
            $data->{'Custom13'} = $object->getCustom13();
        }
        if (null !== $object->getCustom14()) {
            $data->{'Custom14'} = $object->getCustom14();
        }
        if (null !== $object->getCustom15()) {
            $data->{'Custom15'} = $object->getCustom15();
        }
        if (null !== $object->getCustom16()) {
            $data->{'Custom16'} = $object->getCustom16();
        }
        if (null !== $object->getCustom17()) {
            $data->{'Custom17'} = $object->getCustom17();
        }
        if (null !== $object->getCustom18()) {
            $data->{'Custom18'} = $object->getCustom18();
        }
        if (null !== $object->getCustom19()) {
            $data->{'Custom19'} = $object->getCustom19();
        }
        if (null !== $object->getCustom2()) {
            $data->{'Custom2'} = $object->getCustom2();
        }
        if (null !== $object->getCustom20()) {
            $data->{'Custom20'} = $object->getCustom20();
        }
        if (null !== $object->getCustom3()) {
            $data->{'Custom3'} = $object->getCustom3();
        }
        if (null !== $object->getCustom4()) {
            $data->{'Custom4'} = $object->getCustom4();
        }
        if (null !== $object->getCustom5()) {
            $data->{'Custom5'} = $object->getCustom5();
        }
        if (null !== $object->getCustom6()) {
            $data->{'Custom6'} = $object->getCustom6();
        }
        if (null !== $object->getCustom7()) {
            $data->{'Custom7'} = $object->getCustom7();
        }
        if (null !== $object->getCustom8()) {
            $data->{'Custom8'} = $object->getCustom8();
        }
        if (null !== $object->getCustom9()) {
            $data->{'Custom9'} = $object->getCustom9();
        }
        if (null !== $object->getEverSentBack()) {
            $data->{'EverSentBack'} = $object->getEverSentBack();
        }
        if (null !== $object->getHasException()) {
            $data->{'HasException'} = $object->getHasException();
        }
        if (null !== $object->getID()) {
            $data->{'ID'} = $object->getID();
        }
        $data->{'LastComment'} = $object->getLastComment();
        if (null !== $object->getLastModifiedDate()) {
            $data->{'LastModifiedDate'} = $object->getLastModifiedDate();
        }
        $data->{'LedgerName'} = $object->getLedgerName();
        $data->{'Name'} = $object->getName();
        if (null !== $object->getOrgUnit1()) {
            $data->{'OrgUnit1'} = $object->getOrgUnit1();
        }
        if (null !== $object->getOrgUnit2()) {
            $data->{'OrgUnit2'} = $object->getOrgUnit2();
        }
        if (null !== $object->getOrgUnit3()) {
            $data->{'OrgUnit3'} = $object->getOrgUnit3();
        }
        if (null !== $object->getOrgUnit4()) {
            $data->{'OrgUnit4'} = $object->getOrgUnit4();
        }
        if (null !== $object->getOrgUnit5()) {
            $data->{'OrgUnit5'} = $object->getOrgUnit5();
        }
        if (null !== $object->getOrgUnit6()) {
            $data->{'OrgUnit6'} = $object->getOrgUnit6();
        }
        $data->{'OwnerLoginID'} = $object->getOwnerLoginID();
        $data->{'OwnerName'} = $object->getOwnerName();
        $data->{'PaidDate'} = $object->getPaidDate();
        $data->{'PaymentStatusCode'} = $object->getPaymentStatusCode();
        $data->{'PaymentStatusName'} = $object->getPaymentStatusName();
        $data->{'PersonalAmount'} = $object->getPersonalAmount();
        $data->{'PolicyID'} = $object->getPolicyID();
        $data->{'ProcessingPaymentDate'} = $object->getProcessingPaymentDate();
        if (null !== $object->getReceiptsReceived()) {
            $data->{'ReceiptsReceived'} = $object->getReceiptsReceived();
        }
        $data->{'SubmitDate'} = $object->getSubmitDate();
        $data->{'Total'} = $object->getTotal();
        $data->{'TotalApprovedAmount'} = $object->getTotalApprovedAmount();
        $data->{'TotalClaimedAmount'} = $object->getTotalClaimedAmount();
        if (null !== $object->getURI()) {
            $data->{'URI'} = $object->getURI();
        }
        $data->{'UserDefinedDate'} = $object->getUserDefinedDate();
        $data->{'WorkflowActionUrl'} = $object->getWorkflowActionUrl();

        return $data;
    }
}
