<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Concur\Api\Model;

class CreateResponse
{
    /**
     * @var string
     */
    protected $iD;
    /**
     * @var string
     */
    protected $uRI;

    public function getID(): string
    {
        return $this->iD;
    }

    public function setID(string $iD): self
    {
        $this->iD = $iD;

        return $this;
    }

    public function getURI(): string
    {
        return $this->uRI;
    }

    public function setURI(string $uRI): self
    {
        $this->uRI = $uRI;

        return $this;
    }
}
