<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Concur\Api\Model;

class CustomField
{
    /**
     * For list fields, this is the list item code.
     *
     * @var string
     */
    protected $code;
    /**
     * For list fields, this is the list item ID.
     *
     * @var string
     */
    protected $listItemID;
    /**
     * The custom field type. Supported values: Amount, Boolean, ConnectedList, Date, Integer, List, Number, Text.
     *
     * @var string
     */
    protected $type;
    /**
     * The value in the Org Unit or Custom field. For list fields, this is the name of the list item.  Maximum length: 48 characters.
     *
     * @var string
     */
    protected $value;

    /**
     * For list fields, this is the list item code.
     */
    public function getCode(): string
    {
        return $this->code;
    }

    /**
     * For list fields, this is the list item code.
     */
    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    /**
     * For list fields, this is the list item ID.
     */
    public function getListItemID(): string
    {
        return $this->listItemID;
    }

    /**
     * For list fields, this is the list item ID.
     */
    public function setListItemID(string $listItemID): self
    {
        $this->listItemID = $listItemID;

        return $this;
    }

    /**
     * The custom field type. Supported values: Amount, Boolean, ConnectedList, Date, Integer, List, Number, Text.
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * The custom field type. Supported values: Amount, Boolean, ConnectedList, Date, Integer, List, Number, Text.
     */
    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * The value in the Org Unit or Custom field. For list fields, this is the name of the list item.  Maximum length: 48 characters.
     */
    public function getValue(): string
    {
        return $this->value;
    }

    /**
     * The value in the Org Unit or Custom field. For list fields, this is the name of the list item.  Maximum length: 48 characters.
     */
    public function setValue(string $value): self
    {
        $this->value = $value;

        return $this;
    }
}
