<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Concur\Api\Model;

class GeneralDetail
{
    /**
     * @var LineItem
     */
    protected $lineItems;

    public function getLineItems(): LineItem
    {
        return $this->lineItems;
    }

    public function setLineItems(LineItem $lineItems): self
    {
        $this->lineItems = $lineItems;

        return $this;
    }
}
