<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Concur\Api\Model;

class LineItem
{
    /**
     * The total charged amount for the line item. Range: -922,337,203,685,477 to 922,337,203,685,477.
     *
     * @var float
     */
    protected $amount;
    /**
     * The date and time when the line item was charged. Format: YYYY-MM-DDThh:mm.
     *
     * @var \DateTime
     */
    protected $date;
    /**
     * The item's description. Maximum length: 100 characters.
     *
     * @var string
     */
    protected $description;
    /**
     * Additional details about the item. In the receipt image, the secondary description appears on the line following the primary description. Maximum length: 32 characters.
     *
     * @var string
     */
    protected $description2;
    /**
     * The quantity of units. Format: Any positive number.
     *
     * @var int
     */
    protected $quantity;
    /**
     * The amount charged per unit. Range: -922,337,203,685,477 to 922,337,203,685,477.
     *
     * @var float
     */
    protected $rate;
    /**
     * The unit of measure or rate type. Possible values: HOUR or PER HOUR, DAY or PER DAY, WEEK or PER WEEK, MONTH or PER MONTH. Maximum length: 10 characters.
     *
     * @var string
     */
    protected $rateType;
    /**
     * The item's SKU, identifier, or some other attribute the provider uses to reference the item. Maximum length: 32 characters.
     *
     * @var string
     */
    protected $reference;
    /**
     * The order in which the item appears in the sequence of line items.
     *
     * @var int
     */
    protected $sequenceNumber;

    /**
     * The total charged amount for the line item. Range: -922,337,203,685,477 to 922,337,203,685,477.
     */
    public function getAmount(): float
    {
        return $this->amount;
    }

    /**
     * The total charged amount for the line item. Range: -922,337,203,685,477 to 922,337,203,685,477.
     */
    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    /**
     * The date and time when the line item was charged. Format: YYYY-MM-DDThh:mm.
     */
    public function getDate(): \DateTime
    {
        return $this->date;
    }

    /**
     * The date and time when the line item was charged. Format: YYYY-MM-DDThh:mm.
     */
    public function setDate(\DateTime $date): self
    {
        $this->date = $date;

        return $this;
    }

    /**
     * The item's description. Maximum length: 100 characters.
     */
    public function getDescription(): string
    {
        return $this->description;
    }

    /**
     * The item's description. Maximum length: 100 characters.
     */
    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Additional details about the item. In the receipt image, the secondary description appears on the line following the primary description. Maximum length: 32 characters.
     */
    public function getDescription2(): string
    {
        return $this->description2;
    }

    /**
     * Additional details about the item. In the receipt image, the secondary description appears on the line following the primary description. Maximum length: 32 characters.
     */
    public function setDescription2(string $description2): self
    {
        $this->description2 = $description2;

        return $this;
    }

    /**
     * The quantity of units. Format: Any positive number.
     */
    public function getQuantity(): int
    {
        return $this->quantity;
    }

    /**
     * The quantity of units. Format: Any positive number.
     */
    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    /**
     * The amount charged per unit. Range: -922,337,203,685,477 to 922,337,203,685,477.
     */
    public function getRate(): float
    {
        return $this->rate;
    }

    /**
     * The amount charged per unit. Range: -922,337,203,685,477 to 922,337,203,685,477.
     */
    public function setRate(float $rate): self
    {
        $this->rate = $rate;

        return $this;
    }

    /**
     * The unit of measure or rate type. Possible values: HOUR or PER HOUR, DAY or PER DAY, WEEK or PER WEEK, MONTH or PER MONTH. Maximum length: 10 characters.
     */
    public function getRateType(): string
    {
        return $this->rateType;
    }

    /**
     * The unit of measure or rate type. Possible values: HOUR or PER HOUR, DAY or PER DAY, WEEK or PER WEEK, MONTH or PER MONTH. Maximum length: 10 characters.
     */
    public function setRateType(string $rateType): self
    {
        $this->rateType = $rateType;

        return $this;
    }

    /**
     * The item's SKU, identifier, or some other attribute the provider uses to reference the item. Maximum length: 32 characters.
     */
    public function getReference(): string
    {
        return $this->reference;
    }

    /**
     * The item's SKU, identifier, or some other attribute the provider uses to reference the item. Maximum length: 32 characters.
     */
    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    /**
     * The order in which the item appears in the sequence of line items.
     */
    public function getSequenceNumber(): int
    {
        return $this->sequenceNumber;
    }

    /**
     * The order in which the item appears in the sequence of line items.
     */
    public function setSequenceNumber(int $sequenceNumber): self
    {
        $this->sequenceNumber = $sequenceNumber;

        return $this;
    }
}
