<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Concur\Api\Model;

class ListGetCollection
{
    /**
     * @var ListGet[]
     */
    protected $items;
    /**
     * The URI of the next page of results, if any.
     *
     * @var string|null
     */
    protected $nextPage;

    /**
     * @return ListGet[]
     */
    public function getItems(): array
    {
        return $this->items;
    }

    /**
     * @param ListGet[] $items
     */
    public function setItems(array $items): self
    {
        $this->items = $items;

        return $this;
    }

    /**
     * The URI of the next page of results, if any.
     */
    public function getNextPage(): ?string
    {
        return $this->nextPage;
    }

    /**
     * The URI of the next page of results, if any.
     */
    public function setNextPage(?string $nextPage): self
    {
        $this->nextPage = $nextPage;

        return $this;
    }
}
