<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Concur\Api\Model;

class ListItemGet
{
    /**
     * The unique identifier of the resource.
     *
     * @var string
     */
    protected $iD;
    /**
     * The item code for the tenth level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     *
     * @var string|null
     */
    protected $level10Code;
    /**
     * The item code for the first level of the list. All lists have at least a Level1Code. Maximum 32 characters.
     *
     * @var string|null
     */
    protected $level1Code;
    /**
     * The item code for the second level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     *
     * @var string|null
     */
    protected $level2Code;
    /**
     * The item code for the third level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     *
     * @var string|null
     */
    protected $level3Code;
    /**
     * The item code for the fourth level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     *
     * @var string|null
     */
    protected $level4Code;
    /**
     * The item code for the fifth level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     *
     * @var string|null
     */
    protected $level5Code;
    /**
     * The item code for the sixth level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     *
     * @var string|null
     */
    protected $level6Code;
    /**
     * The item code for the seventh level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     *
     * @var string|null
     */
    protected $level7Code;
    /**
     * The item code for the eighth level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     *
     * @var string|null
     */
    protected $level8Code;
    /**
     * The item code for the ninth level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     *
     * @var string|null
     */
    protected $level9Code;
    /**
     * The unique identifier for the list this item is a member of.
     *
     * @var string
     */
    protected $listID;
    /**
     * The name of item. Maximum 64 characters.
     *
     * @var string|null
     */
    protected $name;
    /**
     * The unique identifier of this item's parent. Empty when there is no parent.
     *
     * @var string|null
     */
    protected $parentID;
    /**
     * The URI to the resource.
     *
     * @var string
     */
    protected $uRI;

    /**
     * The unique identifier of the resource.
     */
    public function getID(): string
    {
        return $this->iD;
    }

    /**
     * The unique identifier of the resource.
     */
    public function setID(string $iD): self
    {
        $this->iD = $iD;

        return $this;
    }

    /**
     * The item code for the tenth level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     */
    public function getLevel10Code(): ?string
    {
        return $this->level10Code;
    }

    /**
     * The item code for the tenth level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     */
    public function setLevel10Code(?string $level10Code): self
    {
        $this->level10Code = $level10Code;

        return $this;
    }

    /**
     * The item code for the first level of the list. All lists have at least a Level1Code. Maximum 32 characters.
     */
    public function getLevel1Code(): ?string
    {
        return $this->level1Code;
    }

    /**
     * The item code for the first level of the list. All lists have at least a Level1Code. Maximum 32 characters.
     */
    public function setLevel1Code(?string $level1Code): self
    {
        $this->level1Code = $level1Code;

        return $this;
    }

    /**
     * The item code for the second level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     */
    public function getLevel2Code(): ?string
    {
        return $this->level2Code;
    }

    /**
     * The item code for the second level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     */
    public function setLevel2Code(?string $level2Code): self
    {
        $this->level2Code = $level2Code;

        return $this;
    }

    /**
     * The item code for the third level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     */
    public function getLevel3Code(): ?string
    {
        return $this->level3Code;
    }

    /**
     * The item code for the third level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     */
    public function setLevel3Code(?string $level3Code): self
    {
        $this->level3Code = $level3Code;

        return $this;
    }

    /**
     * The item code for the fourth level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     */
    public function getLevel4Code(): ?string
    {
        return $this->level4Code;
    }

    /**
     * The item code for the fourth level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     */
    public function setLevel4Code(?string $level4Code): self
    {
        $this->level4Code = $level4Code;

        return $this;
    }

    /**
     * The item code for the fifth level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     */
    public function getLevel5Code(): ?string
    {
        return $this->level5Code;
    }

    /**
     * The item code for the fifth level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     */
    public function setLevel5Code(?string $level5Code): self
    {
        $this->level5Code = $level5Code;

        return $this;
    }

    /**
     * The item code for the sixth level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     */
    public function getLevel6Code(): ?string
    {
        return $this->level6Code;
    }

    /**
     * The item code for the sixth level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     */
    public function setLevel6Code(?string $level6Code): self
    {
        $this->level6Code = $level6Code;

        return $this;
    }

    /**
     * The item code for the seventh level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     */
    public function getLevel7Code(): ?string
    {
        return $this->level7Code;
    }

    /**
     * The item code for the seventh level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     */
    public function setLevel7Code(?string $level7Code): self
    {
        $this->level7Code = $level7Code;

        return $this;
    }

    /**
     * The item code for the eighth level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     */
    public function getLevel8Code(): ?string
    {
        return $this->level8Code;
    }

    /**
     * The item code for the eighth level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     */
    public function setLevel8Code(?string $level8Code): self
    {
        $this->level8Code = $level8Code;

        return $this;
    }

    /**
     * The item code for the ninth level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     */
    public function getLevel9Code(): ?string
    {
        return $this->level9Code;
    }

    /**
     * The item code for the ninth level of the list. Empty when this level doesn't exist in the list. Maximum 32 characters.
     */
    public function setLevel9Code(?string $level9Code): self
    {
        $this->level9Code = $level9Code;

        return $this;
    }

    /**
     * The unique identifier for the list this item is a member of.
     */
    public function getListID(): string
    {
        return $this->listID;
    }

    /**
     * The unique identifier for the list this item is a member of.
     */
    public function setListID(string $listID): self
    {
        $this->listID = $listID;

        return $this;
    }

    /**
     * The name of item. Maximum 64 characters.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * The name of item. Maximum 64 characters.
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * The unique identifier of this item's parent. Empty when there is no parent.
     */
    public function getParentID(): ?string
    {
        return $this->parentID;
    }

    /**
     * The unique identifier of this item's parent. Empty when there is no parent.
     */
    public function setParentID(?string $parentID): self
    {
        $this->parentID = $parentID;

        return $this;
    }

    /**
     * The URI to the resource.
     */
    public function getURI(): string
    {
        return $this->uRI;
    }

    /**
     * The URI to the resource.
     */
    public function setURI(string $uRI): self
    {
        $this->uRI = $uRI;

        return $this;
    }
}
