<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Concur\Api\Model;

class Location
{
    /**
     * The provider's street address. Maximum length: 100 characters.
     *
     * @var string
     */
    protected $address;
    /**
     * The provider's secondary street address. Maximum length: 50 characters.
     *
     * @var string
     */
    protected $address2;
    /**
     * The provider's city. Maximum length: 100 characters.
     *
     * @var string
     */
    protected $city;
    /**
     * The provider's country. Format: <a target="_blank" href="http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2">2-letter ISO 3166-1 country code</a>.
     *
     * @var string
     */
    protected $countryCode;
    /**
     * The provider's state, province, or other country subdivision. Format: <a target="_blank" href="http://en.wikipedia.org/wiki/ISO_3166-2">ISO 3166-2:2007 country subdivision</a> code YYY, where YYY is the one-to-three–character subdivision code.
     *
     * @var string
     */
    protected $countrySubdivisionCode;
    /**
     * The provider's email address. Maximum length: 255 characters.
     *
     * @var string
     */
    protected $emailAddress;
    /**
     * The provider's fax number. Maximum length: 32 characters.
     *
     * @var string
     */
    protected $faxNumber;
    /**
     * The provider's Web address. Maximum length: 255 characters.
     *
     * @var string
     */
    protected $internetAddress;
    /**
     * The name of the provider's location, such as an airport, car rental agency, property, store, or other named location. Maximum length: 100 characters.
     *
     * @var string
     */
    protected $name;
    /**
     * The provider's postal code. Maximum length: 20 characters.
     *
     * @var string
     */
    protected $postalCode;
    /**
     * The provider's telephone number. Maximum length: 100 characters.
     *
     * @var string
     */
    protected $telephoneNumber;

    /**
     * The provider's street address. Maximum length: 100 characters.
     */
    public function getAddress(): string
    {
        return $this->address;
    }

    /**
     * The provider's street address. Maximum length: 100 characters.
     */
    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    /**
     * The provider's secondary street address. Maximum length: 50 characters.
     */
    public function getAddress2(): string
    {
        return $this->address2;
    }

    /**
     * The provider's secondary street address. Maximum length: 50 characters.
     */
    public function setAddress2(string $address2): self
    {
        $this->address2 = $address2;

        return $this;
    }

    /**
     * The provider's city. Maximum length: 100 characters.
     */
    public function getCity(): string
    {
        return $this->city;
    }

    /**
     * The provider's city. Maximum length: 100 characters.
     */
    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    /**
     * The provider's country. Format: <a target="_blank" href="http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2">2-letter ISO 3166-1 country code</a>.
     */
    public function getCountryCode(): string
    {
        return $this->countryCode;
    }

    /**
     * The provider's country. Format: <a target="_blank" href="http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2">2-letter ISO 3166-1 country code</a>.
     */
    public function setCountryCode(string $countryCode): self
    {
        $this->countryCode = $countryCode;

        return $this;
    }

    /**
     * The provider's state, province, or other country subdivision. Format: <a target="_blank" href="http://en.wikipedia.org/wiki/ISO_3166-2">ISO 3166-2:2007 country subdivision</a> code YYY, where YYY is the one-to-three–character subdivision code.
     */
    public function getCountrySubdivisionCode(): string
    {
        return $this->countrySubdivisionCode;
    }

    /**
     * The provider's state, province, or other country subdivision. Format: <a target="_blank" href="http://en.wikipedia.org/wiki/ISO_3166-2">ISO 3166-2:2007 country subdivision</a> code YYY, where YYY is the one-to-three–character subdivision code.
     */
    public function setCountrySubdivisionCode(string $countrySubdivisionCode): self
    {
        $this->countrySubdivisionCode = $countrySubdivisionCode;

        return $this;
    }

    /**
     * The provider's email address. Maximum length: 255 characters.
     */
    public function getEmailAddress(): string
    {
        return $this->emailAddress;
    }

    /**
     * The provider's email address. Maximum length: 255 characters.
     */
    public function setEmailAddress(string $emailAddress): self
    {
        $this->emailAddress = $emailAddress;

        return $this;
    }

    /**
     * The provider's fax number. Maximum length: 32 characters.
     */
    public function getFaxNumber(): string
    {
        return $this->faxNumber;
    }

    /**
     * The provider's fax number. Maximum length: 32 characters.
     */
    public function setFaxNumber(string $faxNumber): self
    {
        $this->faxNumber = $faxNumber;

        return $this;
    }

    /**
     * The provider's Web address. Maximum length: 255 characters.
     */
    public function getInternetAddress(): string
    {
        return $this->internetAddress;
    }

    /**
     * The provider's Web address. Maximum length: 255 characters.
     */
    public function setInternetAddress(string $internetAddress): self
    {
        $this->internetAddress = $internetAddress;

        return $this;
    }

    /**
     * The name of the provider's location, such as an airport, car rental agency, property, store, or other named location. Maximum length: 100 characters.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * The name of the provider's location, such as an airport, car rental agency, property, store, or other named location. Maximum length: 100 characters.
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * The provider's postal code. Maximum length: 20 characters.
     */
    public function getPostalCode(): string
    {
        return $this->postalCode;
    }

    /**
     * The provider's postal code. Maximum length: 20 characters.
     */
    public function setPostalCode(string $postalCode): self
    {
        $this->postalCode = $postalCode;

        return $this;
    }

    /**
     * The provider's telephone number. Maximum length: 100 characters.
     */
    public function getTelephoneNumber(): string
    {
        return $this->telephoneNumber;
    }

    /**
     * The provider's telephone number. Maximum length: 100 characters.
     */
    public function setTelephoneNumber(string $telephoneNumber): self
    {
        $this->telephoneNumber = $telephoneNumber;

        return $this;
    }
}
