<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Concur\Api\Model;

class MatchingFact
{
    /**
     * The type of matching fact that is used to identify the Concur user who owns the receipt. Possible values: OAuth, Login.
     *
     * @var string
     */
    protected $type;
    /**
     * The value of the matching fact. If the Type element is set to OAuth, this value must be the access token for the Concur user who owns the receipt. In this case, the access token must not be expired or revoked. If the Type element is set to Login, this value must be the login ID of the Concur user who owns the receipt.
     *
     * @var string
     */
    protected $value;

    /**
     * The type of matching fact that is used to identify the Concur user who owns the receipt. Possible values: OAuth, Login.
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * The type of matching fact that is used to identify the Concur user who owns the receipt. Possible values: OAuth, Login.
     */
    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * The value of the matching fact. If the Type element is set to OAuth, this value must be the access token for the Concur user who owns the receipt. In this case, the access token must not be expired or revoked. If the Type element is set to Login, this value must be the login ID of the Concur user who owns the receipt.
     */
    public function getValue(): string
    {
        return $this->value;
    }

    /**
     * The value of the matching fact. If the Type element is set to OAuth, this value must be the access token for the Concur user who owns the receipt. In this case, the access token must not be expired or revoked. If the Type element is set to Login, this value must be the login ID of the Concur user who owns the receipt.
     */
    public function setValue(string $value): self
    {
        $this->value = $value;

        return $this;
    }
}
