<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Concur\Api\Model;

class ReceiptCustomField
{
    /**
     * The name of the custom field. Maximum length: 128 characters.
     *
     * @var string
     */
    protected $name;
    /**
     * The value of the custom field. Maximum length: 256 characters.
     *
     * @var string
     */
    protected $value;

    /**
     * The name of the custom field. Maximum length: 128 characters.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * The name of the custom field. Maximum length: 128 characters.
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * The value of the custom field. Maximum length: 256 characters.
     */
    public function getValue(): string
    {
        return $this->value;
    }

    /**
     * The value of the custom field. Maximum length: 256 characters.
     */
    public function setValue(string $value): self
    {
        $this->value = $value;

        return $this;
    }
}
