<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Concur\Api\Model;

class ReceiptImage
{
    /**
     * The unique identifier of the resource.
     *
     * @var string
     */
    protected $iD;
    /**
     * The URI to the resource.
     *
     * @var string
     */
    protected $uRI;

    /**
     * The unique identifier of the resource.
     */
    public function getID(): string
    {
        return $this->iD;
    }

    /**
     * The unique identifier of the resource.
     */
    public function setID(string $iD): self
    {
        $this->iD = $iD;

        return $this;
    }

    /**
     * The URI to the resource.
     */
    public function getURI(): string
    {
        return $this->uRI;
    }

    /**
     * The URI to the resource.
     */
    public function setURI(string $uRI): self
    {
        $this->uRI = $uRI;

        return $this;
    }
}
