<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Concur\Api\Model;

class ReportPut
{
    /**
     * The report header comment. Maximum length: 500.
     *
     * @var string
     */
    protected $comment;
    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $custom1;
    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $custom10;
    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $custom11;
    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $custom12;
    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $custom13;
    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $custom14;
    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $custom15;
    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $custom16;
    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $custom17;
    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $custom18;
    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $custom19;
    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $custom2;
    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $custom20;
    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $custom3;
    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $custom4;
    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $custom5;
    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $custom6;
    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $custom7;
    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $custom8;
    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $custom9;
    /**
     * The name of the report.
     *
     * @var string
     */
    protected $name;
    /**
     * The details from the Org Unit fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $orgUnit1;
    /**
     * The details from the Org Unit fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $orgUnit2;
    /**
     * The details from the Org Unit fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $orgUnit3;
    /**
     * The details from the Org Unit fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $orgUnit4;
    /**
     * The details from the Org Unit fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $orgUnit5;
    /**
     * The details from the Org Unit fields. These may not have data, depending on configuration.
     *
     * @var string
     */
    protected $orgUnit6;
    /**
     * The unique identifier for the policy. This is the protected Policy Key.
     *
     * @var string
     */
    protected $policyID;
    /**
     * The business purpose of the report. Maximum length: 500.
     *
     * @var string
     */
    protected $purpose;
    /**
     * The date of the report assigned by the user.
     *
     * @var \DateTime
     */
    protected $userDefinedDate;

    /**
     * The report header comment. Maximum length: 500.
     */
    public function getComment(): string
    {
        return $this->comment;
    }

    /**
     * The report header comment. Maximum length: 500.
     */
    public function setComment(string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function getCustom1(): string
    {
        return $this->custom1;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function setCustom1(string $custom1): self
    {
        $this->custom1 = $custom1;

        return $this;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function getCustom10(): string
    {
        return $this->custom10;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function setCustom10(string $custom10): self
    {
        $this->custom10 = $custom10;

        return $this;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function getCustom11(): string
    {
        return $this->custom11;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function setCustom11(string $custom11): self
    {
        $this->custom11 = $custom11;

        return $this;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function getCustom12(): string
    {
        return $this->custom12;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function setCustom12(string $custom12): self
    {
        $this->custom12 = $custom12;

        return $this;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function getCustom13(): string
    {
        return $this->custom13;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function setCustom13(string $custom13): self
    {
        $this->custom13 = $custom13;

        return $this;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function getCustom14(): string
    {
        return $this->custom14;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function setCustom14(string $custom14): self
    {
        $this->custom14 = $custom14;

        return $this;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function getCustom15(): string
    {
        return $this->custom15;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function setCustom15(string $custom15): self
    {
        $this->custom15 = $custom15;

        return $this;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function getCustom16(): string
    {
        return $this->custom16;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function setCustom16(string $custom16): self
    {
        $this->custom16 = $custom16;

        return $this;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function getCustom17(): string
    {
        return $this->custom17;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function setCustom17(string $custom17): self
    {
        $this->custom17 = $custom17;

        return $this;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function getCustom18(): string
    {
        return $this->custom18;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function setCustom18(string $custom18): self
    {
        $this->custom18 = $custom18;

        return $this;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function getCustom19(): string
    {
        return $this->custom19;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function setCustom19(string $custom19): self
    {
        $this->custom19 = $custom19;

        return $this;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function getCustom2(): string
    {
        return $this->custom2;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function setCustom2(string $custom2): self
    {
        $this->custom2 = $custom2;

        return $this;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function getCustom20(): string
    {
        return $this->custom20;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function setCustom20(string $custom20): self
    {
        $this->custom20 = $custom20;

        return $this;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function getCustom3(): string
    {
        return $this->custom3;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function setCustom3(string $custom3): self
    {
        $this->custom3 = $custom3;

        return $this;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function getCustom4(): string
    {
        return $this->custom4;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function setCustom4(string $custom4): self
    {
        $this->custom4 = $custom4;

        return $this;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function getCustom5(): string
    {
        return $this->custom5;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function setCustom5(string $custom5): self
    {
        $this->custom5 = $custom5;

        return $this;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function getCustom6(): string
    {
        return $this->custom6;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function setCustom6(string $custom6): self
    {
        $this->custom6 = $custom6;

        return $this;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function getCustom7(): string
    {
        return $this->custom7;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function setCustom7(string $custom7): self
    {
        $this->custom7 = $custom7;

        return $this;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function getCustom8(): string
    {
        return $this->custom8;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function setCustom8(string $custom8): self
    {
        $this->custom8 = $custom8;

        return $this;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function getCustom9(): string
    {
        return $this->custom9;
    }

    /**
     * The details from the Custom fields. These may not have data, depending on configuration.
     */
    public function setCustom9(string $custom9): self
    {
        $this->custom9 = $custom9;

        return $this;
    }

    /**
     * The name of the report.
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * The name of the report.
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * The details from the Org Unit fields. These may not have data, depending on configuration.
     */
    public function getOrgUnit1(): string
    {
        return $this->orgUnit1;
    }

    /**
     * The details from the Org Unit fields. These may not have data, depending on configuration.
     */
    public function setOrgUnit1(string $orgUnit1): self
    {
        $this->orgUnit1 = $orgUnit1;

        return $this;
    }

    /**
     * The details from the Org Unit fields. These may not have data, depending on configuration.
     */
    public function getOrgUnit2(): string
    {
        return $this->orgUnit2;
    }

    /**
     * The details from the Org Unit fields. These may not have data, depending on configuration.
     */
    public function setOrgUnit2(string $orgUnit2): self
    {
        $this->orgUnit2 = $orgUnit2;

        return $this;
    }

    /**
     * The details from the Org Unit fields. These may not have data, depending on configuration.
     */
    public function getOrgUnit3(): string
    {
        return $this->orgUnit3;
    }

    /**
     * The details from the Org Unit fields. These may not have data, depending on configuration.
     */
    public function setOrgUnit3(string $orgUnit3): self
    {
        $this->orgUnit3 = $orgUnit3;

        return $this;
    }

    /**
     * The details from the Org Unit fields. These may not have data, depending on configuration.
     */
    public function getOrgUnit4(): string
    {
        return $this->orgUnit4;
    }

    /**
     * The details from the Org Unit fields. These may not have data, depending on configuration.
     */
    public function setOrgUnit4(string $orgUnit4): self
    {
        $this->orgUnit4 = $orgUnit4;

        return $this;
    }

    /**
     * The details from the Org Unit fields. These may not have data, depending on configuration.
     */
    public function getOrgUnit5(): string
    {
        return $this->orgUnit5;
    }

    /**
     * The details from the Org Unit fields. These may not have data, depending on configuration.
     */
    public function setOrgUnit5(string $orgUnit5): self
    {
        $this->orgUnit5 = $orgUnit5;

        return $this;
    }

    /**
     * The details from the Org Unit fields. These may not have data, depending on configuration.
     */
    public function getOrgUnit6(): string
    {
        return $this->orgUnit6;
    }

    /**
     * The details from the Org Unit fields. These may not have data, depending on configuration.
     */
    public function setOrgUnit6(string $orgUnit6): self
    {
        $this->orgUnit6 = $orgUnit6;

        return $this;
    }

    /**
     * The unique identifier for the policy. This is the protected Policy Key.
     */
    public function getPolicyID(): string
    {
        return $this->policyID;
    }

    /**
     * The unique identifier for the policy. This is the protected Policy Key.
     */
    public function setPolicyID(string $policyID): self
    {
        $this->policyID = $policyID;

        return $this;
    }

    /**
     * The business purpose of the report. Maximum length: 500.
     */
    public function getPurpose(): string
    {
        return $this->purpose;
    }

    /**
     * The business purpose of the report. Maximum length: 500.
     */
    public function setPurpose(string $purpose): self
    {
        $this->purpose = $purpose;

        return $this;
    }

    /**
     * The date of the report assigned by the user.
     */
    public function getUserDefinedDate(): \DateTime
    {
        return $this->userDefinedDate;
    }

    /**
     * The date of the report assigned by the user.
     */
    public function setUserDefinedDate(\DateTime $userDefinedDate): self
    {
        $this->userDefinedDate = $userDefinedDate;

        return $this;
    }
}
