<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Concur\Api\Model;

class RideDetail
{
    /**
     * The name of the driver. Maximum length: 255 characters.
     *
     * @var string
     */
    protected $driverName;
    /**
     * The latitude of the ride end location. Range: -90 to 90.
     *
     * @var float
     */
    protected $dropoffLatitude;
    /**
     * The longitude of the ride end location. Range: -180 to 180.
     *
     * @var float
     */
    protected $dropoffLongitude;
    /**
     * The ending date and time for the ride. Format: YYYY-MM-DDThh:mm.
     *
     * @var \DateTime
     */
    protected $endDateTime;
    /**
     * @var LineItem
     */
    protected $lineItems;
    /**
     * The starting date and time for the ride. Format: YYYY-MM-DDThh:mm.
     *
     * @var \DateTime
     */
    protected $startDateTime;
    /**
     * The unique identifier for the vehicle. Maximum length: 50 characters.
     *
     * @var string
     */
    protected $vehicleNumber;

    /**
     * The name of the driver. Maximum length: 255 characters.
     */
    public function getDriverName(): string
    {
        return $this->driverName;
    }

    /**
     * The name of the driver. Maximum length: 255 characters.
     */
    public function setDriverName(string $driverName): self
    {
        $this->driverName = $driverName;

        return $this;
    }

    /**
     * The latitude of the ride end location. Range: -90 to 90.
     */
    public function getDropoffLatitude(): float
    {
        return $this->dropoffLatitude;
    }

    /**
     * The latitude of the ride end location. Range: -90 to 90.
     */
    public function setDropoffLatitude(float $dropoffLatitude): self
    {
        $this->dropoffLatitude = $dropoffLatitude;

        return $this;
    }

    /**
     * The longitude of the ride end location. Range: -180 to 180.
     */
    public function getDropoffLongitude(): float
    {
        return $this->dropoffLongitude;
    }

    /**
     * The longitude of the ride end location. Range: -180 to 180.
     */
    public function setDropoffLongitude(float $dropoffLongitude): self
    {
        $this->dropoffLongitude = $dropoffLongitude;

        return $this;
    }

    /**
     * The ending date and time for the ride. Format: YYYY-MM-DDThh:mm.
     */
    public function getEndDateTime(): \DateTime
    {
        return $this->endDateTime;
    }

    /**
     * The ending date and time for the ride. Format: YYYY-MM-DDThh:mm.
     */
    public function setEndDateTime(\DateTime $endDateTime): self
    {
        $this->endDateTime = $endDateTime;

        return $this;
    }

    public function getLineItems(): LineItem
    {
        return $this->lineItems;
    }

    public function setLineItems(LineItem $lineItems): self
    {
        $this->lineItems = $lineItems;

        return $this;
    }

    /**
     * The starting date and time for the ride. Format: YYYY-MM-DDThh:mm.
     */
    public function getStartDateTime(): \DateTime
    {
        return $this->startDateTime;
    }

    /**
     * The starting date and time for the ride. Format: YYYY-MM-DDThh:mm.
     */
    public function setStartDateTime(\DateTime $startDateTime): self
    {
        $this->startDateTime = $startDateTime;

        return $this;
    }

    /**
     * The unique identifier for the vehicle. Maximum length: 50 characters.
     */
    public function getVehicleNumber(): string
    {
        return $this->vehicleNumber;
    }

    /**
     * The unique identifier for the vehicle. Maximum length: 50 characters.
     */
    public function setVehicleNumber(string $vehicleNumber): self
    {
        $this->vehicleNumber = $vehicleNumber;

        return $this;
    }
}
