<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Concur\Api\Model;

class User
{
    /**
     * Indicates whether the user is currently active or not.
     *
     * @var bool
     */
    protected $active;
    /**
     * The cell phone number of the user.
     *
     * @var string|null
     */
    protected $cellPhoneNumber;
    /**
     * The employee ID of the user.
     *
     * @var string|null
     */
    protected $employeeID;
    /**
     * The first name of the user.
     *
     * @var string|null
     */
    protected $firstName;
    /**
     * The unique identifier of the resource.
     *
     * @var string|null
     */
    protected $iD;
    /**
     * The last name of the user.
     *
     * @var string|null
     */
    protected $lastName;
    /**
     * The login ID of the user.
     *
     * @var string|null
     */
    protected $loginID;
    /**
     * The middle name of the user.
     *
     * @var string|null
     */
    protected $middleName;
    /**
     * The organization unit of the user.
     *
     * @var string|null
     */
    protected $organizationUnit;
    /**
     * The primary email of the user.
     *
     * @var string|null
     */
    protected $primaryEmail;
    /**
     * The URI to the resource.
     *
     * @var string|null
     */
    protected $uRI;

    /**
     * Indicates whether the user is currently active or not.
     */
    public function getActive(): bool
    {
        return $this->active;
    }

    /**
     * Indicates whether the user is currently active or not.
     */
    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    /**
     * The cell phone number of the user.
     */
    public function getCellPhoneNumber(): ?string
    {
        return $this->cellPhoneNumber;
    }

    /**
     * The cell phone number of the user.
     */
    public function setCellPhoneNumber(?string $cellPhoneNumber): self
    {
        $this->cellPhoneNumber = $cellPhoneNumber;

        return $this;
    }

    /**
     * The employee ID of the user.
     */
    public function getEmployeeID(): ?string
    {
        return $this->employeeID;
    }

    /**
     * The employee ID of the user.
     */
    public function setEmployeeID(?string $employeeID): self
    {
        $this->employeeID = $employeeID;

        return $this;
    }

    /**
     * The first name of the user.
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /**
     * The first name of the user.
     */
    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * The unique identifier of the resource.
     */
    public function getID(): ?string
    {
        return $this->iD;
    }

    /**
     * The unique identifier of the resource.
     */
    public function setID(?string $iD): self
    {
        $this->iD = $iD;

        return $this;
    }

    /**
     * The last name of the user.
     */
    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    /**
     * The last name of the user.
     */
    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * The login ID of the user.
     */
    public function getLoginID(): ?string
    {
        return $this->loginID;
    }

    /**
     * The login ID of the user.
     */
    public function setLoginID(?string $loginID): self
    {
        $this->loginID = $loginID;

        return $this;
    }

    /**
     * The middle name of the user.
     */
    public function getMiddleName(): ?string
    {
        return $this->middleName;
    }

    /**
     * The middle name of the user.
     */
    public function setMiddleName(?string $middleName): self
    {
        $this->middleName = $middleName;

        return $this;
    }

    /**
     * The organization unit of the user.
     */
    public function getOrganizationUnit(): ?string
    {
        return $this->organizationUnit;
    }

    /**
     * The organization unit of the user.
     */
    public function setOrganizationUnit(?string $organizationUnit): self
    {
        $this->organizationUnit = $organizationUnit;

        return $this;
    }

    /**
     * The primary email of the user.
     */
    public function getPrimaryEmail(): ?string
    {
        return $this->primaryEmail;
    }

    /**
     * The primary email of the user.
     */
    public function setPrimaryEmail(?string $primaryEmail): self
    {
        $this->primaryEmail = $primaryEmail;

        return $this;
    }

    /**
     * The URI to the resource.
     */
    public function getURI(): ?string
    {
        return $this->uRI;
    }

    /**
     * The URI to the resource.
     */
    public function setURI(?string $uRI): self
    {
        $this->uRI = $uRI;

        return $this;
    }
}
