<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Concur\Api\Endpoint;

class GetExpenseReport extends \Jane\OpenApiRuntime\Client\BaseEndpoint implements \Jane\OpenApiRuntime\Client\Psr7Endpoint
{
    /**
     * Returns all reports owned by the user based on the search criteria.
     *
     * @param array $queryParameters {
     *
     *     @var string $offset Starting page offset
     *     @var int $limit Number of records to return (default 25)
     *     @var string $user Optional. The login ID of the report owner(s) to use when searching for reports. If the value is set to LoginID, reports for the report owner with this login ID value are returned. If the value is set to ALL, reports for all report owners are returned. If this parameter is not specified, reports for the OAuth Consumer are returned. The access token owner (OAuth Consumer) must have the Web Services Admin role to use this parameter.
     *     @var string $approvalStatusCode The status code for the Approval Status. The values can include Concur Expense standard codes or custom codes. The Concur Expense standard code values are: A_AAFH - Report submission triggered an anomaly and fraud check; A_ACCO - Report is pending reviews; A_APPR - Report has been approved; A_EXTV - Report is pending external validation; A_FILE - Report has been submitted; A_NOTF - Report has not been submitted; A_PBDG - Report approval is pending Budget approval; A_PECO - Report approval is pending Cost object approval; A_PEND - Report is pending manager approval; A_PVAL - Report is pending prepayment validation; A_RESU - Report needs to be resubmitted; A_RHLD - Report submission is pending receipt images; A_TEXP - Report expired in approval queue. For custom codes, contact Concur Developer Support.
     *     @var string $paymentStatusCode The payment status code for the report. The values can include Concur Expense standard codes or custom codes. The Concur Expense standard code values are: P_HOLD - Report payment is on hold; P_NOTP - Report has not been paid; P_PAID - Report has been paid; P_PAYC - Payment is confirmed. Some or all of the report expenses have been paid; P_PROC - Report is in process to be paid. For custom codes, contact Concur Developer Support.
     *     @var string $currencyCode The 3-letter ISO 4217 currency code for the report currency. Example: USD.
     *     @var string $paymentType The unique identifier for the payment type that is the payment type for at least one expense entry in the report. Use PaymentTypeID from the "GET Expense Group Configurations" function.
     *     @var string $reimbursementMethod The method the report owner will be reimbursed. VALUES: ADPPAYR - ADP Payroll; APCHECK - AP (Company Check); CNQRPAY - Expense Pay; PMTSERV - Other Payment Service. NOTE: PAY_PAL is NOT supported.
     *     @var string $approverLoginID the login ID for the report approver that is the current approver assigned to the report
     *     @var string $expenseTypeCode The expense type code that is the expense type for at least one expense entry in the report. Use ExpenseTypeCode from the "GET Expense Group Configurations" function.
     *     @var string $attendeeTypeCode the report contains expense entries that have attendees of the specified type
     *     @var string $countryCode The report country. Maximum 2 characters. Format: The ISO 3166-1 alpha-2 country code. Example: United States is US.
     *     @var string $batchID The unique identifier for a payment batch where there is at least one report payee within the report. Use the BatchID from the "GET Payment Batch List" function.
     *     @var string $vendorName the Vendor Description that is the vendor for at least one expense entry in the report
     *     @var bool $hasVAT Determines if the report has at least one expense entry with VAT details. Format: true or false.
     *     @var bool $hasImages Determines if the report has at least one expense entry with an entry image or if there is a report image for this report. Format: true or false.
     *     @var bool $hasAttendees Determines if the report has at least one expense entry with an attendee. Format: true or false.
     *     @var bool $hasBillableExpenses The IsBillable flag for at least one expense entry in the report. Format: true or false.
     *     @var bool $isTestUser The report owner is a test user using the report for testing purposes in a non-production envirnment. format: true or false.
     *     @var string $expenseGroupConfigID The unique identifier for the expense group configuration associated to the report's expense group. Use the ID from the "GET Expense Group Configurations" function.
     *     @var string $entryTransactionDateBefore The entry transaction date for at least one expense entry in the report is before this date.Format: YYYY-MM-DD
     *     @var string $entryTransactionDateAfter The entry transaction date for at least one expense entry in the report is after this date.Format: YYYY-MM-DD
     *     @var string $createDateBefore The report create date is before this date.Format: YYYY-MM-DD
     *     @var string $createDateAfter The report create date is after this date.Format: YYYY-MM-DD
     *     @var string $userDefinedDateBefore The report user defined date is before this date.Format: YYYY-MM-DD
     *     @var string $userDefinedDateAfter The report user defined date is after this date.Format: YYYY-MM-DD
     *     @var string $submitDateBefore The report submit date is before this date.Format: YYYY-MM-DD
     *     @var string $submitDateAfter The report submit date is after this date.Format: YYYY-MM-DD
     *     @var string $processingPaymentDateBefore The report processing payment date is before this date.Format: YYYY-MM-DD
     *     @var string $processingPaymentDateAfter The report processing payment date is after this date. Format: YYYY-MM-DD
     *     @var string $paidDateBefore The report paid date is before this date.Format: YYYY-MM-DD
     *     @var string $paidDateAfter The report paid date is after this date.Format: YYYY-MM-DD
     *     @var string $modifiedDateBefore The report modified date is before this date.Format: YYYY-MM-DD
     *     @var string $modifiedDateAfter The report modified date is after this date.Format: YYYY-MM-DD
     * }
     */
    public function __construct(array $queryParameters = [])
    {
        $this->queryParameters = $queryParameters;
    }

    use \Jane\OpenApiRuntime\Client\Psr7EndpointTrait;

    public function getMethod(): string
    {
        return 'GET';
    }

    public function getUri(): string
    {
        return '/expense/reports';
    }

    public function getBody(\Symfony\Component\Serializer\SerializerInterface $serializer, $streamFactory = null): array
    {
        return [[], null];
    }

    public function getExtraHeaders(): array
    {
        return ['Accept' => ['application/json']];
    }

    protected function getQueryOptionsResolver(): \Symfony\Component\OptionsResolver\OptionsResolver
    {
        $optionsResolver = parent::getQueryOptionsResolver();
        $optionsResolver->setDefined(['offset', 'limit', 'user', 'approvalStatusCode', 'paymentStatusCode', 'currencyCode', 'paymentType', 'reimbursementMethod', 'approverLoginID', 'expenseTypeCode', 'attendeeTypeCode', 'countryCode', 'batchID', 'vendorName', 'hasVAT', 'hasImages', 'hasAttendees', 'hasBillableExpenses', 'isTestUser', 'expenseGroupConfigID', 'entryTransactionDateBefore', 'entryTransactionDateAfter', 'createDateBefore', 'createDateAfter', 'userDefinedDateBefore', 'userDefinedDateAfter', 'submitDateBefore', 'submitDateAfter', 'processingPaymentDateBefore', 'processingPaymentDateAfter', 'paidDateBefore', 'paidDateAfter', 'modifiedDateBefore', 'modifiedDateAfter']);
        $optionsResolver->setRequired([]);
        $optionsResolver->setDefaults([]);
        $optionsResolver->setAllowedTypes('offset', ['string']);
        $optionsResolver->setAllowedTypes('limit', ['int']);
        $optionsResolver->setAllowedTypes('user', ['string']);
        $optionsResolver->setAllowedTypes('approvalStatusCode', ['string']);
        $optionsResolver->setAllowedTypes('paymentStatusCode', ['string']);
        $optionsResolver->setAllowedTypes('currencyCode', ['string']);
        $optionsResolver->setAllowedTypes('paymentType', ['string']);
        $optionsResolver->setAllowedTypes('reimbursementMethod', ['string']);
        $optionsResolver->setAllowedTypes('approverLoginID', ['string']);
        $optionsResolver->setAllowedTypes('expenseTypeCode', ['string']);
        $optionsResolver->setAllowedTypes('attendeeTypeCode', ['string']);
        $optionsResolver->setAllowedTypes('countryCode', ['string']);
        $optionsResolver->setAllowedTypes('batchID', ['string']);
        $optionsResolver->setAllowedTypes('vendorName', ['string']);
        $optionsResolver->setAllowedTypes('hasVAT', ['bool']);
        $optionsResolver->setAllowedTypes('hasImages', ['bool']);
        $optionsResolver->setAllowedTypes('hasAttendees', ['bool']);
        $optionsResolver->setAllowedTypes('hasBillableExpenses', ['bool']);
        $optionsResolver->setAllowedTypes('isTestUser', ['bool']);
        $optionsResolver->setAllowedTypes('expenseGroupConfigID', ['string']);
        $optionsResolver->setAllowedTypes('entryTransactionDateBefore', ['string']);
        $optionsResolver->setAllowedTypes('entryTransactionDateAfter', ['string']);
        $optionsResolver->setAllowedTypes('createDateBefore', ['string']);
        $optionsResolver->setAllowedTypes('createDateAfter', ['string']);
        $optionsResolver->setAllowedTypes('userDefinedDateBefore', ['string']);
        $optionsResolver->setAllowedTypes('userDefinedDateAfter', ['string']);
        $optionsResolver->setAllowedTypes('submitDateBefore', ['string']);
        $optionsResolver->setAllowedTypes('submitDateAfter', ['string']);
        $optionsResolver->setAllowedTypes('processingPaymentDateBefore', ['string']);
        $optionsResolver->setAllowedTypes('processingPaymentDateAfter', ['string']);
        $optionsResolver->setAllowedTypes('paidDateBefore', ['string']);
        $optionsResolver->setAllowedTypes('paidDateAfter', ['string']);
        $optionsResolver->setAllowedTypes('modifiedDateBefore', ['string']);
        $optionsResolver->setAllowedTypes('modifiedDateAfter', ['string']);

        return $optionsResolver;
    }

    /**
     * {@inheritdoc}
     *
     * @return \Concur\Api\Model\ReportCollection|null
     */
    protected function transformResponseBody(string $body, int $status, \Symfony\Component\Serializer\SerializerInterface $serializer, ?string $contentType = null)
    {
        if (200 === $status && mb_strpos($contentType, 'application/json') !== false) {
            return $serializer->deserialize($body, 'Concur\\Api\\Model\\ReportCollection', 'json');
        }
    }
}
